id: IBC4CB9AD
ocr_import_info:
  bdrc_scan_id: W3CN4963
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-03-08 20:23:31.318256
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4963
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4963
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡིད་བཞིན་རིན་པོ་ཆེའི་མཛོད་རྩ་འགྲེལ།
  languages:
  - bo
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
bases:
  I3CN4965:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4965
      total_pages: 518
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I3CN4965.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
